name: fashion_brand_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.4.0
  dot_bottom_navigation_bar_getx: ^0.0.1
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.1
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  http: ^1.2.2
  intl: ^0.19.0
  path: ^1.9.0
  sqflite: ^2.3.3+1
  upi_india: ^3.0.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: acme
      fonts:
        - asset: assets/fonts/Acme-Regular.ttf